name: Anton Klima
analytics: {}
purpose:
  - type: external
    url: 'http://www.schlag-agentur.de/index.php/de/camera/profile/anton_klima'
    label: contact
  - type: contact
    url: 'tel:3235786777'
    label: direct
github: true
description: cinematographer
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/897750a6-2d2b-41c0-bac8-6c2004eec302.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/897750a6-2d2b-41c0-bac8-6c2004eec302.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.795885205558953
color:
  lightness: 0.25380446406606916
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  saturation: 0.03089507925988055
  brandStrength: 0.6516728087125512
  rhythmicContrast: 0.7983964179422116
content_rating:
  adult: false
typography_spectrum: 0.07745221146493045
opengraph: {}
title: Anton Klima
